### PR TITLE
Products

### PR DESCRIPTION
**Pull request by ciscoflores**
This PR:

**Add:**
- Class Products which contains the methods
  - _list_ to get all the products
  - _findByID_ to get the information of a specific product
  - _findByPermalink_ to get the information of a specific product
  - _create_ to add a new product
  - _delete_ to remove a product
  - _update_ to update attributes of a product
  - _search_
- APICall class, which is a small function to do the API requests.

**Modify:**
- Class Products methods to use APICall method to do requests to the Solidus API

### CODE REVIEW

**Comment by oguzman** [comment]
This APICall abstraction looks great, I ran tests and everything is working as expected; I think we can offer either RESTManager and APICall, both can grow up.

**Comment by oguzman** [comment]
@ciscoflores there is nothing existing like this in the ransack search, devs are used to create a "predicate" to make the query in this part, so; I think we would change to string instead of params array.

**Comment by ciscoflores** [comment]
So @oguzman you consider that _RansackQuery_ implementation is useless or unnecessary?

**Comment by oguzman** [comment]
No, its only diferent, so we could go with the standard and only use the predicate feature

**Comment by oguzman** [comment]
I've changed instance methods to class methods, also ransack query was changed to predicate string; I'll open another pull request

**Pull request merged**
