### PR TITLE
Orders and Cities

### PR DESCRIPTION
**Pull request by oguzman**
Endpoints and tests for Orders and Cities have been done.

### CODE REVIEW

**Comment by oguzman** [comment]
@softr8 Merge has been done; all tests have passed. Thanks!

**Comment by oguzman** [comment]
Also code style has been fixed ;) thanks.

**Comment by ciscoflores** [comment]
@oguzman I have trouble with the _callback_ which contains a _success_ and _result_. Because from my point of view is more clearly to have a _result/data_ and an _error_. I know if the _success_ is false means there's an error.

**Comment by oguzman** [comment]
@ciscoflores what's your suggestion for the response?

**Comment by ciscoflores** [comment]
@oguzman I suggest and actually what I'm doing is returning a _result_ and an _error_ in each method/call to the API. Like this `products.showByPermalink("product") { (result, error) in`

**Comment by oguzman** [comment]
So you did modified the RESTManager? and you're returning "callback(json, error) instead of callback(false || true, json)?

**Comment by ciscoflores** [comment]
Actually, I'm not using the _RESTManager_, I'm using plain _NSURLSession_. As I told you, I want first to have this approach and in the next iteration look on how to get a smart manager to talk with Solidus API.

**Comment by oguzman** [comment]
@ciscoflores I've updated the RESTManager and unit tests to return "Error" when something happens on a service call, could you please take a look. Thanks.

**Comment by ciscoflores** [comment]
@oguzman  two things:
**1.-** Is _accessTokenInHeader_ still used in the _RESTManager_?
**2.-** According with the style code, the _else_ has to be in the same line that the rounded bracket **}** like `} else {`

**Comment by oguzman** [comment]
accessTokenInHeader is not used yet, but I'm sure we will need it; and regarding coding style I'm fixing it (where did you read that rule?)

**Comment by ciscoflores** [comment]
@oguzman I saw it in the Apple documentation and in the link supplied by @softr8

**Comment by oguzman** [comment]
screen shot 2016-05-09 at 4 56 51 pm
I'm checking some swift native classes, and else seems this way...

**Comment by ciscoflores** [comment]
@oguzman  
This is a screenshot from the _Apple_ documentation website. I didn't look in code from the frameworks and I know that code _objetive-c_, but the style code can be applied very similar.

screen shot 2016-05-09 at 5 00 13 pm

Also check thin [link](https://github.com/raywenderlich/swift-style-guide#closure-expressionsl)

**Comment by oguzman** [comment]
@ciscoflores could you please check the coding style; I've updated the else sentences

**Comment by ciscoflores** [comment]
@oguzman seems like the style code is fine.

**Comment by oguzman** [comment]
;) thanks!

**Comment by oguzman** [comment]
Cities class changed in services from concatenation to interpolation

**Comment by oguzman** [comment]
Here I've updated the methods; All tests are passing success, re-writing looks good to me.

**Comment by oguzman** [comment]
@softr8 could you please take a quick look into naming conventions and let me know your comments?

**Pull request merged**
